name: project_travelplanner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2
  http: ^1.4.0
  image_picker: ^1.1.2
  graphql_flutter: ^5.2.0
  table_calendar: ^3.2.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
