final Map<String, String> provinceImages = {
  'ACEH': 'assets/images/ACEH.jpg',
  'BALI': 'assets/images/BALI.jpg',
  'SUMATERA UTARA': 'assets/images/SUMATERA UTARA.jpg',
  'SUMATERA BARAT': 'assets/images/SUMATERA BARAT.jpg',
  'SUMATERA SELATAN': 'assets/images/SUMATERA SELATAN.jpg',
  'BANTEN': 'assets/images/BANTEN.jpg',
  'BENGKULU': 'assets/images/BENGKULU.jpg',
  'DI YOGYAKARTA': 'assets/images/DI YOGYAKARTA.jpg',
  'DKI JAKARTA': 'assets/images/DKI JAKARTA.jpg',
  'JAMBI': 'assets/images/JAMBI.jpg',
  'JAWA BARAT': 'assets/images/JAWA BARAT.jpg',
  'JAWA TENGAH': 'assets/images/JAWA TENGAH.jpg',
  'JAWA TIMUR': 'assets/images/JAWA TIMUR.jpg',
  'KALIMANTAN BARAT': 'assets/images/KALIMANTAN BARAT.jpg',
  'KALIMANTAN TENGAH': 'assets/images/KALIMANTAN TENGAH.jpg',
  'KEPULAUAN RIAU': 'assets/images/KEPULAUAN RIAU.jpg',
  'KEPULAUAN BANGKA BELITUNG': 'assets/images/KEPULAUAN BANGKA BELITUNG.jpg',
  'LAMPUNG': 'assets/images/LAMPUNG.jpg',
  'NUSA TENGGARA BARAT': 'assets/images/NUSA TENGGARA BARAT.jpg',
  'RIAU': 'assets/images/RIAU.jpg',
  'NUSA TENGGARA TIMUR': 'assets/images/NUSA TENGGARA TIMUR.jpg',
  'KALIMANTAN TIMUR': 'assets/images/KALIMANTAN TIMUR.jpg',
  'KALIMANTAN SELATAN': 'assets/images/KALIMANTAN SELATAN.jpg',
  'KALIMANTAN UTARA': 'assets/images/KALIMANTAN UTARA.jpg',
  'GORONTALO': 'assets/images/GORONTALO.jpg',
  'SULAWESI BARAT': 'assets/images/SULAWESI BARAT.jpg',
  'SULAWESI SELATAN': 'assets/images/SULAWESI SELATAN.jpg',
  'SULAWESI TENGAH': 'assets/images/SULAWESI TENGAH.jpg',
  'SULAWESI TENGGARA': 'assets/images/SULAWESI TENGGARA.jpg',
  'SULAWESI UTARA': 'assets/images/SULAWESI UTARA.jpg',
  'MALUKU': 'assets/images/MALUKU.jpg',
  'MALUKU UTARA': 'assets/images/MALUKU UTARA.jpg',
  'PAPUA': 'assets/images/PAPUA.jpg',
  'PAPUA BARAT': 'assets/images/PAPUA BARAT.jpg',
};
